name: bmaia
description: "La nueva era de la inteligencia artificial."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  flutter_sound: ^9.2.13
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  logging: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.0.4
  characters: ^1.4.0
  lints: ^6.0.0
  flutter_markdown: ^0.7.4+1
  dio: ^5.9.0
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  flutter_tts: ^4.2.3
  connectivity_plus: ^7.0.0
  speech_to_text: ^7.3.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
