name: bmaia
description: "La nueva era de la inteligencia artificial."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  flutter_sound: ^9.2.13
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  logging: ^1.2.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"